python3 main.py \
  --use_tpu=False \
  --tpu_name=kevin \
  --do_train=True \
  --do_eval=True \
  --sup_train_data_dir=$GS/uda/text/data/proc_data/IMDB/pseudo/bt-0.9/0 \
  --eval_data_dir=$GS/uda/text/data/proc_data/IMDB/dev \
  --bert_config_file=$GS/uda/text/pretrained_models/bert_base/bert_config.json \
  --vocab_file=$GS/uda/text/pretrained_models/bert_base/vocab.txt \
  --init_checkpoint=$GS/uda/text/pretrained_models/bert_base/bert_model.ckpt \
  --task_name=IMDB \
  --model_dir=$GS/uda/text/ckpt/bt_0.9_0 \
  --num_train_steps=30000 \
  --learning_rate=1e-05 \
  --num_warmup_steps=3000 \
  --max_seq_length=${MAX_SEQ_LENGTH}
